services:
  app:
    restart: unless-stopped
    container_name: flowback-frontend
    image: flowback-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    ports:
      - 3000:3000
    env_file:
      - .env